"""empty message.

Revision ID: 3901262688be
Revises: 675b389fc204
Create Date: 2024-06-07 15:33:27.927922
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3901262688be"
down_revision = "675b389fc204"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_details",
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_details")
    # ### end Alembic commands ###
